In [1]:
import pandas as pd

df = pd.read_csv("preprocessed_data.csv")

In [2]:
df.head()

,event_type,latitude,longitude,event_cause,requires_road_closure,veh_type,corridor,priority,police_station,hour,day_of_week,month
0,1,13.040004,77.518099,14,0,4,19,1,39,17,4,3
1,1,12.921876,77.645158,14,0,2,12,1,15,4,5,1
2,1,12.955622,77.585708,6,0,5,11,0,51,6,2,11
3,1,13.006147,77.579435,13,1,5,11,0,43,17,4,3
4,1,12.953980,77.585233,14,0,6,11,0,51,4,5,1

In [3]:
X = df.drop("priority", axis=1)
y = df["priority"]

In [4]:
print(X.shape)
print(y.shape)

(8166, 11)
(8166,)

In [5]:
y.head()

0    1
1    1
2    0
3    0
4    0
Name: priority, dtype: int64

In [6]:
X.head()

,event_type,latitude,longitude,event_cause,requires_road_closure,veh_type,corridor,police_station,hour,day_of_week,month
0,1,13.040004,77.518099,14,0,4,19,39,17,4,3
1,1,12.921876,77.645158,14,0,2,12,15,4,5,1
2,1,12.955622,77.585708,6,0,5,11,51,6,2,11
3,1,13.006147,77.579435,13,1,5,11,43,17,4,3
4,1,12.953980,77.585233,14,0,6,11,51,4,5,1

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [9]:
print(X_train.shape)
print(X_test.shape)

(6532, 11)
(1634, 11)

In [10]:
from sklearn.ensemble import RandomForestClassifier

In [11]:
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

In [12]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [13]:
y_pred = model.predict(X_test)

In [14]:
print(y_pred[:10])

[1 1 1 1 0 1 1 0 1 1]

In [15]:
from sklearn.metrics import accuracy_score

In [16]:
accuracy = accuracy_score(
    y_test,
    y_pred
)

print("Accuracy:", accuracy)

Accuracy: 0.9987760097919217

In [17]:
from sklearn.metrics import confusion_matrix

In [18]:
cm = confusion_matrix(
    y_test,
    y_pred
)

print(cm)

[[ 623    1]
 [   1 1009]]

In [19]:
from sklearn.metrics import classification_report

In [20]:
print(
    classification_report(
        y_test,
        y_pred
    )
)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       624
           1       1.00      1.00      1.00      1010

    accuracy                           1.00      1634
   macro avg       1.00      1.00      1.00      1634
weighted avg       1.00      1.00      1.00      1634

In [21]:
pd.crosstab(
    df["requires_road_closure"],
    df["priority"]
)

priority                  0     1
requires_road_closure
0                      2760  4732
1                       379   295

In [22]:
df.columns

Index(['event_type', 'latitude', 'longitude', 'event_cause',
       'requires_road_closure', 'veh_type', 'corridor', 'priority',
       'police_station', 'hour', 'day_of_week', 'month'],
      dtype='str')

In [23]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print(importance)

                  Feature  Importance
6                corridor    0.755283
2               longitude    0.090846
1                latitude    0.063879
7          police_station    0.057846
3             event_cause    0.008966
8                    hour    0.006743
5                veh_type    0.004397
10                  month    0.003930
9             day_of_week    0.003621
4   requires_road_closure    0.003527
0              event_type    0.000964

In [24]:
X_v2 = df[[
    "event_type",
    "event_cause",
    "requires_road_closure",
    "veh_type",
    "hour",
    "day_of_week",
    "month"
]]

y_v2 = df["priority"]

In [25]:
print(X_v2.columns)

Index(['event_type', 'event_cause', 'requires_road_closure', 'veh_type',
       'hour', 'day_of_week', 'month'],
      dtype='str')

In [26]:
print(X_v2.shape)
print(y_v2.shape)

(8166, 7)
(8166,)

In [27]:
from sklearn.model_selection import train_test_split

X_train_v2, X_test_v2, y_train_v2, y_test_v2 = train_test_split(
    X_v2,
    y_v2,
    test_size=0.2,
    random_state=42
)

In [28]:
print(X_train_v2.shape)
print(X_test_v2.shape)

(6532, 7)
(1634, 7)

In [29]:
from sklearn.ensemble import RandomForestClassifier

In [30]:
priority_model_v2 = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

In [31]:
priority_model_v2.fit(
    X_train_v2,
    y_train_v2
)

RandomForestClassifier(random_state=42)

In [32]:
y_pred_v2 = priority_model_v2.predict(
    X_test_v2
)

In [33]:
print(y_pred_v2[:10])

[1 1 1 1 1 1 1 1 1 1]

In [34]:
from sklearn.metrics import accuracy_score

accuracy_v2 = accuracy_score(
    y_test_v2,
    y_pred_v2
)

print("Accuracy:", accuracy_v2)

Accuracy: 0.6009791921664627

In [35]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test_v2,
        y_pred_v2
    )
)

              precision    recall  f1-score   support

           0       0.47      0.42      0.44       624
           1       0.67      0.71      0.69      1010

    accuracy                           0.60      1634
   macro avg       0.57      0.57      0.57      1634
weighted avg       0.59      0.60      0.60      1634

In [36]:
from sklearn.metrics import confusion_matrix

cm_v2 = confusion_matrix(
    y_test_v2,
    y_pred_v2
)

print(cm_v2)

[[261 363]
 [289 721]]

In [37]:
importance_v2 = pd.DataFrame({
    "Feature": X_v2.columns,
    "Importance": priority_model_v2.feature_importances_
})

importance_v2 = importance_v2.sort_values(
    by="Importance",
    ascending=False
)

print(importance_v2)

                 Feature  Importance
4                   hour    0.380319
5            day_of_week    0.203741
6                  month    0.153382
3               veh_type    0.117741
1            event_cause    0.115535
2  requires_road_closure    0.018773
0             event_type    0.010510

In [38]:
import joblib

joblib.dump(
    priority_model_v2,
    "priority_model.pkl"
)

['priority_model.pkl']